name: Github release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release-apk:
    name: Validation android
    uses: alexis-gss/github-workflows/.github/workflows/release-apk.yml@master
    with:
      app_name: orion
    secrets: inherit
